function sendmsg(to,subject,message,attachments)
%SENDMSG uses matlab SENDMAIL function to send mail pre-compiled with a set 
% of useful info. The input arguments are the same of SENDMAIL:
%
% sendmail(TO,SUBJECT,MESSAGE,ATTACHMENTS) sends an e-mail.  TO is either a
%     string specifying a single address, or a cell array of addresses.  SUBJECT
%     is a string.  MESSAGE is either a string or a cell array.  If it is a
%     string, the text will automatically wrap at 75 characters.  If it is a cell
%     array, it won't wrap, but each cell starts a new line.  In either case, use
%     char(10) to explicitly specify a new line.  ATTACHMENTS is a string or a
%     cell array of strings listing files to send along with the message. 
%__________________________________________________________________________
%
% Author:
%   Daniele Mascali
%   Enrico Fermi Center, MARBILab, Rome
%   August, 2018
%   danielemascali@gmail.com

global SENDSTATUS_TIC_TIMES

if SENDSTATUS_TIC_TIMES 
    total_elapsed_time = toc(SENDSTATUS_TIC_TIMES(1));
    if length(SENDSTATUS_TIC_TIMES ) == 1 %firt occurrence of sendmsg
        partial_elapsed_time = [];
        SENDSTATUS_TIC_TIMES(end+1) = tic; %append tic times
    else
        partial_elapsed_time = toc(SENDSTATUS_TIC_TIMES(2)); 
        SENDSTATUS_TIC_TIMES(2) = tic; % overwrite the tic time 
    end
end

if nargin == 0
    error('Not enough input arguments. At least one mail address is required.');
end
 
if nargin < 2 
    subject = '';
    message = '';
elseif nargin < 3
    message = '';
end

%empty subj and message are not allowed by sendmail, let's take care of it
if isempty(subject); subject = ''; end
if isempty(message); message = ''; end

%------------CONFIGURE SMTP SERVER and SENDER MAIL-------------------------
sendsetup
%--------------------------------------------------------------------------

if ispc
    username = getenv('username');
    computername = getenv('computername');
elseif isunix || ismac   %not tested on mac
    username = getenv('USER');
    [~, computername] = system('hostname');
    computername = strtrim(computername);
end

ST = dbstack('-completenames');
MainFunction = ST(end);
if ~strcmpi(MainFunction.name,mfilename)
    if strcmpi(ST(2).name,'sendbeacon') %
        % put the machine as prefix of the subject
        subject = ['beacon: ',computername];
    else
        % put the calling function as prefix of the subject
        subject = ['<',MainFunction.name,'> ',subject];
    end
    %and create a info string in the body message
    info_str = sprintf(['by (sub)function: ',ST(2).name,' (at line: ',num2str(ST(2).line),')\n(main function path: ',MainFunction.file,')\n']);
else
    % don't modify the subject.
    %and empty info string in the body message
    info_str = '';
end

               
info_str = sprintf(['Dear %s,\n',...
                           'this message has been generated from: %s\n',...
                           '%s'],username,computername,info_str);
sign_str = sprintf(['Mail generated by: %s\n',...
                    '____________________________\n',...
                    'Automatic Mail Service created by\n',...
                    'Daniele Mascali, PhD\n',...
                    '"Enrico Fermi" Centre\n',...
                    'MARBILab'],ST(1).name);     
                
if SENDSTATUS_TIC_TIMES 
    running_time = ['Total elapsed time:\n',readsec(total_elapsed_time),'\n']; 
    if  not(isempty(partial_elapsed_time))
        running_time = [running_time, 'Elapsed time since last call to sendmsg:\n',readsec(partial_elapsed_time),'\n'];
    end
else
    running_time = '';
end
                
if isempty(message)
    message_final{1} = info_str;
    message_final{2} = sprintf(running_time);
    message_final{3} = sign_str;
else
    message_final{1} = info_str;
    message_final{2} = sprintf([message,'\n']);
    message_final{3} = sprintf(running_time);
    message_final{4} = sign_str; 
end

if nargin <= 3
    sendmail(to,subject,message_final)
else
    sendmail(to,subject,message_final,attachments)
end

return
end